### ISSUE TITLE
Generate list of potential reporting platforms

### ISSUE THREAD

**Issue by mfinholt** [TangerineKenya/Tangerine-Reporting-Team#1]
Generate a list of potential reporting platforms that can be evaluated as a reporting platform for Tangerine deployments.

- [x] Determine evaluation criteria
- [x] Create a master list of technologies to evaluate
- [x] Narrow the list down as far as possible for further evaluation against criteria
- [ ] Choose 1-3 that can be test-deployed for evaluation as a solution

# Evaluation Criteria

- Timeline - can be deployable within the shortened timeline that we have available to us
- Data Source - The solution must be able to natively, or via a custom bridge, support CouchDB
- Data Format - The solution must be able to deal with JSON (unstructured) data
- Licensing - The solution must be Open Source and freely available
- Hosting - The solution must be able to be self-hosted
- Security - Role-based authentication would be ideal but not a must
- Deployment - The solution must be rapidly-deployable - Ideally via a docker container
- Building Charts - The customization of the dashboard contents must be manageable from within the online environment. It is *not* OK to be required to recompile the application or deploy changes directly to the server by someone with adminsitrative access
- Data Manipulation - The solution must some level of data manipulation (aggregation, correlation, etc) from within the design interface when building the charts.

**Comment by mfinholt** [comment]
jshdkjhsdkfjhsdf

- [ ] task 1
- [ ] task2

**Comment by jkisioh** [comment]
- [ ] [JasperReportsServer](http://community.jaspersoft.com/project/jasperreports-server)

**Comment by mfinholt** [comment]
Here is an example of an evaluation that someone else did. While their evaluation criteria are different than ours, I really like the approach that they took.
http://sylvainleroy.com/2017/08/01/TOP-Opensource-dashboard-solutions-2017/
